# Generated by Django 4.1.1 on 2022-09-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemodel',
            name='file',
            field=models.FileField(default=123, upload_to=''),
            preserve_default=False,
        ),
    ]
